config/routes.rb
SproutNotes::Application.routes.draw do

  devise_for :users
  resources :questions do
    resources :comments, :only => [:create, :destroy]
  end
  resources :how_tos do
    resources :comments, :only => [:create, :destroy]
    get 'like'
    get :autocomplete_category_name, :on => :collection
  end

  get "home/index"

  root :to => 'home#index'
  match '/search' => 'home#search', :as => :search
  match "/user" => 'home#user', :as => 'user_root'
  match "/users" => 'home#users', :as => :users
  match "/user/:id" => 'home#user_show', :as => :user_show

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user! , :only => :user

  def index
    @how_tos = HowTo.order_by('created_at', 'DESC').limit(3)
    @questions = Question.order_by('created_at', 'DESC').limit(12)
  end

  def user
    @user = current_user
    @how_tos = current_user.how_tos
    @questions = current_user.questions
  end

  def search
    @how_tos = HowTo.search(params[:search])
  end

  def users
    @users = User.all
  end

  def user_show
    @user = User.find_by_id(params[:id])
    @how_tos = @user.how_tos
    @questions = @user.questions
    render 'user'
  end


end

app/helpers/home_helper.rb
module HomeHelper

  def user_points(user)
    return 15 + user.how_tos.length*50 + user.questions.length*30 + user.comments.length*15
  end

  def display_name(user)
    if user == current_user
      "My"
    else
      user.name + "'s"
    end
  end

end

app/views/home/index.html.haml
#main
  .notes_board.grid_11.alpha
    #main.grid_6.alpha
      %h3 Check It Out
      - @how_tos.each do |how_to|
        .home_note
          = render :partial => "how_tos/how_to_teaser", :locals => { :how_to => how_to }
    #main.grid_5.omega
      %h3 U Can Help
      %ul.question_list
        - @questions.each do |question|
          %li
            = link_to question.title, question_path(question)

app/views/home/search.html.haml
#main.grid_8.alpha
  %ul
    - @how_tos.each do |how_to|
      %li= link_to how_to.title, how_to_path(how_to)

app/views/home/user.html.haml
%h1
  = "#{display_name(@user)} Page"
  = link_to "Edit Profile",edit_user_registration_path if @user == current_user
.notes_board.grid_11.alpha
  #main.grid_6.alpha
    %h3 How Tos
    = link_to "Create a How To", new_how_to_path, :class => "create_question" if @user == current_user
    - @how_tos.each do |how_to|
      = render :partial => "how_tos/how_to_teaser", :locals => { :how_to => how_to }
  #main.grid_5.omega
    %h3 Questions
    = link_to "Ask a Question", new_question_path, :class => "create_question" if @user == current_user
    - @questions.each do |question|
      = render :partial => "questions/question_teaser", :locals => { :question => question }

app/views/home/users.html.haml
= javascript_include_tag 'jquery.tagcloud.min', 'users_tagcloud'
.notes_board
  %h3
    Hall of Fame
  %ul#users_list
    - @users.each do |user|
      %li{:value => "#{user_points(user)}"}
        = link_to user.name, user_show_path(user)