config/routes.rb
SproutNotes::Application.routes.draw do

  devise_for :users
  resources :questions do
    resources :comments, :only => [:create, :destroy]
  end
  resources :how_tos do
    resources :comments, :only => [:create, :destroy]
    get 'like'
    get :autocomplete_category_name, :on => :collection
  end

  get "home/index"

  root :to => 'home#index'
  match '/search' => 'home#search', :as => :search
  match "/user" => 'home#user', :as => 'user_root'
  match "/users" => 'home#users', :as => :users
  match "/user/:id" => 'home#user_show', :as => :user_show

end

app/models/how_to.rb
class HowTo < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments, :as => :commentable, :dependent => :destroy

  validates :title, :presence => true
  validates :description, :presence => true
  validates :instructions, :presence => true

  attr_accessible :title, :description, :instructions, :new_category, :difficulty, :category, :screenshot
  mount_uploader :screenshot, ImageUploader


  before_create :zero_likes
  before_save :default_difficulty, :create_new_category
  after_initialize :default_difficulty

  attr_accessor :new_category

  scope :popular, order('likes DESC')


  def new_category
    return @new_category if @new_category
    return self.category.name if self.category
  end

  def self.order_by(attribute, option)
    order("#{attribute} #{option}")
  end

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    end
  end

  def zero_likes
    self.likes = 0
  end

  def default_difficulty
    if self.difficulty == nil
      self.difficulty = "Medium"
    end
  end

  def create_new_category
    if self.new_category
      category = Category.find_or_create_by_name(self.new_category)
      self.category = category
      return true
    else
      self.errors.add(:new_category, "Category Must Be Present")
      return false
    end
  end

  def to_param
    "#{id}-#{title.parameterize}"  
  end




end

# == Schema Information
#
# Table name: how_tos
#
#  id           :integer         not null, primary key
#  title        :string(255)
#  description  :text
#  difficulty   :string(255)
#  instructions :text
#  likes        :integer
#  category_id  :integer
#  created_at   :datetime
#  updated_at   :datetime
#  user_id      :integer
#

app/controllers/how_tos_controller.rb
class HowTosController < ApplicationController

  before_filter :authenticate_user! , :except => [:index, :show]
  autocomplete :category, :name
  PER_PAGE = 4

  def index
    if params[:category]
      if params[:category] == "*"
        @how_tos = HowTo
      else
        category = Category.find_by_id(params[:category])
        @how_tos = category.how_tos
      end
    else
      @how_tos = HowTo
    end
    if params[:attribute] && params[:order] && params[:search]
      @how_tos = @how_tos.search(params[:search]).order_by(params[:attribute], params[:order])
    elsif params[:attribute] && params[:order]
      @how_tos = @how_tos.order_by(params[:attribute], params[:order])
    elsif params[:search]
      @how_tos = @how_tos.search(params[:search])
    else
      @how_tos = @how_tos.order_by("created_at", "DESC")
    end
    @how_tos = @how_tos.page(params[:page]).per(PER_PAGE)
  end

  def show
    @how_to = HowTo.find(params[:id])
  end

  def new
    @how_to = current_user.how_tos.build
  end

  def create
    @how_to = current_user.how_tos.new(params[:how_to])
    if @how_to.save
      flash[:notice] = "#{@how_to.title} Successfully Created"
      redirect_to how_to_path( @how_to )
    else
      render 'new'
    end
  end

  def edit
    @how_to = current_user.how_tos.find(params[:id])
  end

  def update
    @how_to = current_user.how_tos.find(params[:id])
    if @how_to.update_attributes(params[:how_to])
      flash[:notice] = "Successfully Updated"
      redirect_to how_to_path( @how_to )
    else
      render 'edit'
    end
  end

  def destroy
    how_to = current_user.how_tos.find(params[:id])
    how_to.destroy
    flash[:notice] = "#{how_to.title} Successfully Deleted"
    redirect_to user_root_path
  end

  def like
    @how_to = HowTo.find(params[:how_to_id])
    @how_to.likes = @how_to.likes + 1
    @how_to.save
    session[@how_to.id] = true
    respond_to do |format|
      format.html { redirect_to how_to_path(@how_to) }
      format.js
    end

  end

end

app/helpers/how_tos_helper.rb
module HowTosHelper

  def edit_links ( how_to )
    if how_to.user == current_user
      [
        link_to("Delete", how_to_path(how_to), :method => :delete, :confirm => "Are You Sure???" ),
        link_to("Edit", edit_how_to_path(how_to) ),
      ].join(' ').html_safe
    end
  end

  def how_to_sidebar(title, how_tos)
      arr = []
      how_tos.each do |how_to|
        arr << "<li>#{link_to how_to.title, how_to_path(how_to) }</li>"
      end
      content_tag :aside, :class=> :widget do
        [
          "<h3> #{title} </h3>",
          "<ul>",
          arr,
          "</ul>",
          ].join(' ').html_safe
      end
  end

end

app/views/how_tos/_form.html.haml
#main.grid_8.alpha
  = semantic_form_for @how_to, :html => {:multipart => true} do |f|
    = f.inputs do
      = f.input :title
      = f.input :description, :input_html => { :rows => 5 }
      = f.input :instructions
      = f.input :screenshot, :as => :file
      = f.input :difficulty, :as => :select, :collection => ["Easy", "Medium", "Hard"]
      = f.autocompleted_input :new_category, :url => autocomplete_category_name_how_tos_path, :label => "Category", :required => true
    = f.buttons
  = link_to "Cancel", user_root_path
#main.grid_4.omega
  %div#instructions
    %h4 Instructions:
    %p
      \- Supports textile
      %a{ :href => "http://textile.thresholdstate.com/", :class => "textile_link" }
        Try Textile
    %p - To include code in your instructions: wrap it in a code element with attribute lang giving the language
    For Example
    %pre
      :preserve
           &lt;code lang="ruby">
           def hello
            puts "Hello, world!"
           end
           &lt;/code>
    Supported Languages Are
    %pre
      :preserve

            C, C++
            CSS
            Delphi
            diff
            Groovy (beta)
            HTML
            Java
            JavaScript
            JSON
            Nitro-XHTML
            PHP
            Python
            RHTML (ERB+HTML)
            Ruby
            Scheme (beta)
            SQL
            XML
            YAML
  %div#categories
    %h4 Current Categories
    %ul
      - Category.all.each do |category|
        %li
          = category.name
  = javascript_include_tag 'display_categories'

app/views/how_tos/_how_to.html.haml
%article.how_to
  %h2
    = how_to.title
    = edit_links(how_to)
  %span.author
    By
    = link_to(how_to.user.name, user_show_path(how_to.user))
  %span.date
    = formatted_time how_to.created_at
  %span.likes
    Liked By
    %span.no_of_likes
      = how_to.likes
    |
    = link_to("Like", how_to_like_path(how_to), :remote => true) if !session[how_to.id] && how_to.user != current_user && user_signed_in?
  %p.description
    = how_to.description
  %span.author
    Difficulty:
    = how_to.difficulty
  %span.date
    Category:
    =  how_to.category.name
  %div.instructions
    = textilize(coderay(how_to.instructions)).html_safe
  - if how_to.screenshot.to_s
    %div#screenshot_thumbnail
      %span Screenshot
      = image_tag how_to.screenshot.to_s, :class => "thumbnail", :alt => "Click to View Larger Image"
    %div#screenshot{ :title => "Screenshot"}
      = image_tag how_to.screenshot.to_s

app/views/how_tos/_how_to_teaser.html.haml
%article.teaser
  %h4
    = link_to how_to.title, how_to_path(how_to)
  %span.author
    By #{how_to.user.name}
  %span.date
    On #{how_to.created_at.to_date}
  %span.likes
    Liked By: #{how_to.likes}
  %p.description
    = how_to.description.slice(0..100)+"..."

app/views/how_tos/autocomplete_category.js.erb
<%= auto_complete_result @categories, :name %>

app/views/how_tos/autocomplete_category.js.haml
= auto_complete_result @categories, :name

app/views/how_tos/edit.html.haml
%h1 Edit
= render 'form'

app/views/how_tos/index.html.haml
#main.grid_12.alpha

  %span Order By:
  = form_tag how_tos_path, :method => :get do
    = select_tag :attribute, options_for_select([["Date","created_at"], ["Popularity","likes"], ["Title","title"]], params[:attribute])
    = select_tag :order, options_for_select(["DESC","ASC"], params[:order])
    = select_tag :category, options_for_select( [["All","*"]]+Category.all.map{ |c| [c.name, c.id] } , params[:category])
    = text_field_tag :search, params[:search]
    = submit_tag "Filter"

  .notes_board
    %h3 How Tos
    - @how_tos.each do |how_to|
      .home_note
        = render :partial => "how_to_teaser", :locals => { :how_to => how_to }
    = paginate @how_tos

app/views/how_tos/like.js.erb
$('.no_of_likes').html("<%= @how_to.likes %>");
$('.likes a').hide();

app/views/how_tos/new.html.haml
%h1 How To
= render 'form'

app/views/how_tos/show.html.haml
#main.grid_8.alpha
  = render @how_to
  = render :partial => "/comments/comments", :locals => { :commentable => @how_to }
#sidebar.grid_4.omega
  = how_to_sidebar("Related",@how_to.category.how_tos.popular.limit(5) )
  = how_to_sidebar("Top",HowTo.popular.limit(5) )