config/routes.rb
SproutNotes::Application.routes.draw do

  devise_for :users
  resources :questions do
    resources :comments, :only => [:create, :destroy]
  end
  resources :how_tos do
    resources :comments, :only => [:create, :destroy]
    get 'like'
    get :autocomplete_category_name, :on => :collection
  end

  get "home/index"

  root :to => 'home#index'
  match '/search' => 'home#search', :as => :search
  match "/user" => 'home#user', :as => 'user_root'
  match "/users" => 'home#users', :as => :users
  match "/user/:id" => 'home#user_show', :as => :user_show

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SproutNotes
    = stylesheet_link_tag '960', 'formtastic', 'jquery-ui-1.8.11.custom', 'pink_theme', 'style', 'coderay'
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js'
    = javascript_include_tag 'rails', 'autocomplete-rails', 'application'
    = csrf_meta_tag
  %body
    #wrapper.container_12
      %header#header.grid_12
        %h1= link_to "Sprout Notes", :root
        #login_links
          - if user_signed_in?
            %span.user_name= current_user.name
            = link_to "My page", user_root_path
            = link_to "Log out",destroy_user_session_path
          - else
            = link_to "Sign In",new_user_session_path
            = link_to "Sign Up",new_user_registration_path
        = form_tag(how_tos_path, :method => "get") do
          = text_field_tag :search, params[:search]
          = submit_tag("Search")
      #content
        %nav
          %ul#menu.clearfix
            - if user_signed_in?
              %li= link_to "My page", user_root_path
            %li= link_to "Home", :root
            %li= link_to "HowTos", how_tos_path
            %li= link_to "Questions", questions_path
            %li= link_to "Hall of Fame", users_path
          %p.notice= notice
          %p.alert= alert
        = yield
      %footer#footer.grid_12
        %p
          Copyright &copy; 2011
          %a{:href => "#"} Sprout Technologies